### ISSUE TITLE
[safe_z_home] not working with sensorless homing

### ISSUE THREAD

**Issue by eraxar** [Rat-Rig/v-core-3-klipper-config#1]
hiho, small issue if you have sensorless homing activated. With [homing_override] klipper dont like that [safe_z_home] is activated in 300/400/500.cfg too.
maybe put [safe_z_home] in the printer.cfg we can deactivate it?

**Comment by miklschmidt** [comment]
Should be solved in the latest release. [safe_z_home] now needs to be configured in printer.cfg (included in the vcoreos image).
